// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder() {
  return window['go']['editor']['FileHandler']['OpenFolder']();
}

export function Startup(arg1) {
  return window['go']['editor']['FileHandler']['Startup'](arg1);
}
