// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile() {
  return window['go']['editor']['Folder']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['editor']['Folder']['OpenFolder']();
}

export function Startup(arg1) {
  return window['go']['editor']['Folder']['Startup'](arg1);
}
