// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';
import {context} from '../models';

export function OpenFile():Promise<string>;

export function OpenFolder():Promise<editor.FolderContent>;

export function Startup(arg1:context.Context):Promise<void>;
